### PR TITLE
Deprecate TrivialDriveKotlin

### PR DESCRIPTION
**Pull request by calren**
Based on feedback from https://github.com/android/play-billing-samples/issues/427 and https://github.com/android/play-billing-samples/issues/405, we've decided to deprecate the existing TrivialDriveKotlin.

Our plan is to create a new minimalist sample similar to the original [TrivialDrive](https://github.com/android/play-billing-samples/tree/7a94c6905a9c125518354c216b5c3094fde47ce1/TrivialDrive), using Kotlin and Play Billing Library 3.0 to start.

The new sample will contain just one [MainActivity](https://github.com/android/play-billing-samples/blob/7a94c6905a9c125518354c216b5c3094fde47ce1/TrivialDrive/app/src/main/java/com/example/android/trivialdrivesample/MainActivity.java) to help demonstrate the main usages of the Play Billing Library.

### CODE REVIEW

**Comment by LordByron1788** [comment]
Can you deliver a replacement to this sample before you deprecate TrivialDriveKotlin?

You are effectively, leaving us with nothing, which is what you did with the Java Trivial Drive version (which was still very much in demand - see #278).

You should also communicate clearly what is going to replace TrivialDriveKotlin and when it will be delivered to avoid situations like in #260 (where the wrong thing was communicated).

**Comment by khanhnt3010** [comment]
@LordByron1788 me too, waiting for 20 days from owner :(

**Comment by stephanedupont** [comment]
> You are effectively, leaving us with nothing

This is really all what is needed to implement the billing (and is available in Java):
https://developer.android.com/google/play/billing/integrate

I really don't think there needs to be a sample, the library is easy to use.

**Comment by calren** [comment]
closing in favor of https://github.com/android/play-billing-samples/pull/441

**Pull request closed without merging**
