### PR TITLE
fixed NullPointerException, "mService" will be set to be null, when "onServiceDisconnected()" be called.

### PR DESCRIPTION
**Pull request by BigXiaoYang**
we found some NullPointerException, the reason is the parameter "mService" of IabHelper is null sometimes.
I think this parameter will be set to be null when "onServiceDisconnected()" called.
so I think you need check if the parameter is null when to use it.

### CODE REVIEW

**Comment by BigXiaoYang** [comment]
Hi, I signed it.

**Comment by BigXiaoYang** [comment]
I signed it.

**Comment by jakubkrolewski** [comment]
It looks like an important fix. @BigXiaoYang will you try fixing the problem with the license agreement?

**Comment by rpattabi** [comment]
Why is the service becoming null? Probably IabHelper disposed and we are still making calls to it. We shall probably prevent such a situation from happening instead of resorting to null checks.

**Comment by treert** [comment]
I find a way to create this situation.
1. Open your app, init IAP.
2. Then Switch google account in android system account setting,
3. return to your app, now service is disconnected.

**Comment by calren** [comment]
Thanks for having submit this pull request to help us maintain our samples! Unfortunately we decided to [deprecate TrivialDrive](https://github.com/android/play-billing-samples/commit/b0ca34426ca7bddfbcb0557e195ea69898320440) as we were getting feedback from developers that having multiple samples was confusing.

Since the sample is now deprecated, I'm going to go ahead and close this PR. But we definitely encourage you to continue contributing to our existing samples!

**Pull request closed without merging**
