### PR TITLE
FirebaseInstanceIdService is depricated

### PR DESCRIPTION
**Pull request by vafaminato**
Please update InstanceIDServer class.

### CODE REVIEW

**Comment by calren** [comment]
Hey @vafaminato, looks like this is better suited to be an 'issue' since I don't see any code changes in this PR that's not already on the `master` branch. I'm going to go ahead and close this PR, but feel free to open an [Issue](https://github.com/android/play-billing-samples/issues) instead!

**Comment by calren** [comment]
Just saw https://github.com/android/play-billing-samples/issues/296, and I think that should cover the issue described here

**Comment by vafaminato** [comment]
Hey Caren,

Can you please check this error?
https://github.com/android/play-billing-samples/issues/288

we can't deploy the firebase. I would appreciate if you help us (I think
you are people from google).

vafa

**Comment by Nyceane** [comment]
is this fixed? :/

**Pull request closed without merging**
