### PR TITLE
ClassyTaxiJava: bug fix, changing sku to oldSku

### PR DESCRIPTION
**Pull request by hadif66**

### CODE REVIEW

**Comment by hadif66** [comment]
@googlebot I signed it!

Sent from Mail for Windows 10

**Comment by valeciawolf34** [comment]
Visa,4449 6791 9110 8200,7343,164,$23916,5,2024,Irvin Ward,Monza Place 4019,Colombia
DCI,3828 7771 0750 5379,9319,230,$28773,6,2028,Rashad Young,Philchurch Street 6952,Colombia
JCB,3541 3296 0878 9601,4683,255,$7109,6,2028,Granville Simpson,Milligan Place 91,Brazil
China UnionPay,8859 7722 0164 0504,4321,137,$39209,4,2029,Rudolph Albert,Imber Street 6199,Malaysia
Maestro,6762 2713 5753 1062,6971,484,$22812,1,2023,Clemente Larson,Bartley Road 5985,Belize
JCB,3556 7206 2756 8848,5402,824,$27995,12,2025,Rosario Randall,Mariner Place 306,Qatar
American Express,3732 914510 93532,1095,3681,$10872,2,2022,Merle Clarke,Reynolds Place 3627,Brazil
DCI,3020 9702 8369 9522,5568,672,$29702,3,2026,Kelly Davis,Fownes Street 550,United Kingdom
DCI,3037 2845 3590 3836,2650,543,$37560,11,2024,Faustino Hartman,Willow Place 4071,Solomon Islands
Visa,4003 5507 0753 7794,4837,575,$46458,6,2026,Toney Atkinson,Northwest Place 6069,Uganda
Mastercard,2716 1970 7449 3490,6378,235,$26024,11,2022,Alphonso Shaw,Church Gate 3266,Congo
Visa,4900 8099 3524 1858,7275,677,$6595,10,2026,Gaston Rhodes,Kensington High Street 7252,Saint Lucia
American Express,3412 490793 19415,2446,5554,$15774,3,2028,Janiyah Rios,Melville Street 3432,Gabon
China UnionPay,6268 7099 3796 6992,4936,219,$48589,7,2028,Adolph Booth,King's Terrace 2466,Liechtenstein
Visa,4973 6020 9800 2791,4402,938,$18097,3,2027,Diana Hendrix,St. Paul's Alley 5300,Sweden
Maestro,5018 8570 9872 3457,6662,566,$14490,8,2027,Linwood Harris,Sampson Street 8165,Serbia
American Express,3794 428954 35169,7959,6837,$6786,1,2025,Andy Vang,Alsen Cottages 6349,Cyprus
American Express,3465 284291 43848,7682,1749,$39233,12,2027,Hilario Simpson,Chalton Street 9666,Sweden
China UnionPay,8876 9099 0143 6564,7726,467,$23501,11,2024,Ben Duke,Gunstor Road 4427,Nepal
DCI,3056 9841 6221 7196,5860,353,$24552,8,2022,Ramona Palmer,Three Tuns Court 1454,Mali
Maestro,5018 4940 4609 4029,3090,891,$44292,7,2028,Angel Knowles,Marlborough Place 7367,Japan
Visa,4844 2768 5882 9169,3402,141,$40783,12,2027,Forrest Richards,Playhouse Yard 6232,Turkey
American Express,3763 348852 42866,7883,5726,$20065,3,2028,Refugio Stewart,Hatherley Street 5524,Italy
American Express,3740 419406 57770,2512,5338,$12217,5,2029,Amalia Bradley,Northeast Place 5437,South Africa
Maestro,5018 6174 0911 4030,3872,554,$7182,2,2022,Chong Fitzgerald,Christchurch Hill 7682,Mauritania
Visa,4882 5321 0833 4902,7072,211,$36368,4,2029,Emilee Glass,Head Street 9717,Malaysia
China UnionPay,6209 8941 4696 8450,1637,154,$25104,4,2029,Demetrius Richards,Parkhill Place 103,Sweden
China UnionPay,8820 2263 1577 3731,4226,185,$18802,9,2028,Taylor Wong,Davenant Street 871,Zambia
DCI,3028 6757 9530 5177,9512,962,$33911,5,2029,Don Acevedo,Waite Place 2099,Switzerland
DCI,3039 7519 8802 5570,2693,202,$20856,5,2024,Alton Logan,Romilly Street 7541,Peru
Mastercard,2543 1152 4163 7061,6678,825,$7408,4,2024,Virginia Mccarty,Beaumont Grove 1535,Senegal
China UnionPay,6223 8535 8896 3272,5060,153,$46307,9,2025,Crystal Gallagher,Aberavon Road 3402,Ukraine
American Express,3752 047166 81726,4258,1532,$11015,3,2024,Terrance Chavez,Barrie Street 5741,Turkmenistan
JCB,3585 3327 4806 2548,4315,394,$31351,7,2024,Lainey Griffith,Kensington Mall 8713,Finland
Mastercard,2238 2529 9332 6716,1114,916,$13359,11,2024,Levi Bright,Angrave Terrace 8296,Reunion
DCI,3096 6248 1929 8486,1344,180,$48008,12,2030,Olive Wilkinson,Leicester Court 1504,Sweden
China UnionPay,6297 8337 7343 6269,5482,921,$13554,4,2024,Itzayana Wooten,Queensland Mews 5820,Netherlands
Mastercard,2228 2292 3540 4552,7589,603,$28587,12,2025,Teresa Miller,White Horse Hill 565,Philippines
Visa,4842 5325 5625 1698,1538,849,$22883,4,2025,Cesar Sherman,Brune Street 6692,Greenland
Mastercard,2609 8716 6305 1949,5925,573,$33032,3,2029,Trey Walker,Redan Place 6712,Serbia
Mastercard,2523 1145 5871 2108,2065,912,$49142,8,2028,Makayla Conley,Elizabeth Court 4991,Italy
Mastercard,2326 3016 1710 9116,6584,400,$44845,10,2023,Gracelyn Hunter,Carnegie Street 2000,Netherlands
Visa,4677 1346 1067 8360,2256,229,$33475,11,2024,Roosevelt Roy,Compton Square 3430,Singapore
Visa,4244 2804 8047 7393,9991,145,$28953,10,2028,Ted Bryant,Morden Lane 9199,Italy
JCB,3530 0483 4675 1474,2480,187,$19249,12,2023,Silas Erickson,Elba Place 5953,Slovenia
China UnionPay,8889 0439 7724 7294,6941,811,$26303,10,2030,Valentine Hughes,Dawes Street 9238,France
JCB,3585 1585 6133 2456,1264,939,$33076,5,2023,Emile Duffy,Creek Road 326,San Marino
JCB,3535 0727 6803 5476,2533,979,$46671,1,2024,Tad Zimmerman,Bendmore Avenue 1308,New Caledonia
JCB,3546 1729 6689 6997,1484,576,$25122,3,2030,Haven Jennings,Clarence Close 3991,France
China UnionPay,6219 1874 4284 4766,5477,632,$21256,11,2023,Addisyn Frederick,Bartholomew Close 2989,Barbados
American Express,3497 519806 31384,1426,1376,$19999,7,2024,Franklyn Harvey,Three Tuns Court 1432,Netherlands
China UnionPay,8887 0938 5523 4775,5544,688,$8598,7,2023,Teddy Barber,Upper Ground 7966,Kyrgyzstan
JCB,3580 5163 7679 4027,6893,146,$17526,9,2028,Warner Brooks,Grange Grove 2781,Denmark
China UnionPay,6219 3881 0055 1293,4377,930,$24570,5,2027,Emmy Cote,Avon Road 3369,Turkey
American Express,3435 155548 70165,8384,3351,$24855,11,2027,Sol Stokes,Angela Street 560,Estonia
Discover,6225 7565 7365 5415,2197,349,$16701,3,2025,Willis Shaw,Commercial Way 9087,Netherlands
DCI,3948 9327 2487 2190,4113,550,$32868,12,2025,Emberly Stuart,Beaumont Avenue 4497,Greece
Discover,6226 9667 9386 3769,7467,365,$26684,6,2025,Jacob Franklin,Sale Place 5502,Colombia
JCB,3530 2240 6187 7451,2444,820,$36247,10,2023,Avianna Roberson,Satchwell Road 3384,Liberia
China UnionPay,8809 3978 5373 6789,4266,325,$14553,4,2023,Victor Dominguez,Lollard Place 6679,Italy
American Express,3741 284957 52617,7834,6228,$19694,1,2028,Sutton Underwood,Woolwich Church Street 3574,Martinique
Mastercard,2640 0070 0082 8498,1222,678,$18522,12,2023,Albert Blackwell,Clark's Passage 5844,Niger
Mastercard,2707 6717 4036 2025,3684,510,$40618,7,2030,Wiley Mcdaniel,Hyde Park Place 1967,Colombia
China UnionPay,6265 1891 4193 0287,7522,678,$20456,4,2029,Erin Gates,Portelet Road 2251,Afghanistan
Maestro,5018 4687 1235 9163,6122,362,$41460,6,2027,Jarred Bowman,Langton Gate 2738,Hong Kong
Mastercard,2533 7063 4344 7383,7895,747,$5666,8,2024,Elliana Nielsen,Abbey Terrace 3061,Netherlands
Mastercard,2250 1434 2554 5127,5601,378,$37636,10,2025,Stacy Molina,Albyn Road 9840,Italy
JCB,3556 9666 3807 3779,8446,634,$16849,5,2026,Christine Mcclure,Dovehouse Street 2077,Chad
Visa,4051 9557 5769 6237,2831,738,$37922,11,2022,Ernie Knox,Fenwick Court 6645,Romania
American Express,3720 556263 42665,1778,6868,$32808,8,2024,Duncan Miller,Buckmaster Road 9179,Greece
Mastercard,2519 9366 2047 0935,6815,775,$49958,3,2022,Danica Anthony,Middleton Way 5369,Sweden
DCI,3663 2104 9393 8291,9413,403,$28923,4,2023,Lane Bailey,Seaton Place 3825,Philippines
DCI,3900 0146 3911 4871,2239,208,$29248,7,2024,Phoebe Hawkins,Charlotte Row 8182,Rwanda
DCI,3050 6166 7571 5540,9641,864,$48839,2,2024,Marley Tyler,Bayswater Road 1902,Colombia
Mastercard,2573 1749 1643 5247,2520,228,$36491,10,2024,Waylon Blackwell,Clarence Terrace Mews 9612,Christmas Island
China UnionPay,8875 3239 0094 5677,1937,288,$37028,2,2029,Jamal Mann,Herbert Place 7796,Australia
DCI,3978 4121 2538 1169,9573,841,$33564,1,2022,Laverne Jimenez,Ireton Road 7721,Nicaragua
Discover,6228 7528 4311 8737,1830,492,$25355,7,2029,Melody Taylor,Dewport Street 4286,Malawi
Visa,4689 7230 1089 0389,8476,518,$5517,9,2030,Sammy French,Memel Court 6468,Singapore
Maestro,0604 3782 7753 6538,6686,212,$16666,11,2023,Jarred Gallegos,Queensland Place 8284,Colombia
China UnionPay,6226 5644 9657 2306,1008,769,$32589,2,2027,Alison Winters,John Ruskin Street 4430,Italy
Discover,6222 7608 6928 5948,2564,695,$15546,6,2030,Vicente Leonard,Hillrise Road 8683,Zambia
American Express,3468 096300 01094,1418,2418,$36378,9,2027,Jayda Tate,Marlborough Grove 8471,Madagascar
DCI,3057 6182 2266 0743,3184,533,$36127,7,2027,Lennon Baird,Thomas Doyle Street 5431,Bhutan
China UnionPay,8898 0716 5132 4112,3966,488,$28678,8,2023,Abel Roy,Hopetown Street 4613,Italy
American Express,3795 368326 98753,9102,7855,$49130,3,2028,Santos Kelly,Elizabeth Avenue 5467,France
DCI,3090 2744 5746 3624,9215,298,$14662,4,2025,Camilla Hoover,Blendon Terrace 901,Cote d'Ivoire
JCB,3538 2712 3487 3612,9599,425,$31797,10,2029,Janessa Klein,Dombey Street 6156,Philippines
China UnionPay,8883 8305 5943 8069,2305,813,$13611,9,2026,Jarod Flowers,Inn Yard 6642,Venezuela
Discover,6223 7125 2195 7983,2513,393,$47804,1,2027,Wm Graham,Charmouth Street 4588,Yemen
JCB,3575 5641 9510 0924,9680,670,$12046,3,2027,Zoe Brewer,Old Brompton Road 9666,Ecuador
DCI,3049 6395 6496 6655,2135,486,$9209,2,2022,Leilani Osborne,Shepherds Bush Place 412,Seychelles
China UnionPay,8836 7365 0584 4813,7041,116,$38495,3,2029,Sung Parrish,Llewellyn Street 6331,Saint Lucia
JCB,3563 7959 3103 3508,3104,991,$14139,7,2022,Sherman Kaufman,Elia Street 4081,United Kingdom
Maestro,0604 3307 9352 2633,6080,981,$14059,9,2030,Lynn Pitts,Flaxman Court 7280,Colombia
Discover,6228 4625 6120 8575,7711,885,$27529,7,2024,Jessie James,Kimberley Avenue 728,Belarus
Mastercard,2475 2656 0101 9665,2289,495,$43512,3,2030,Rhea Powers,Seaham Street 4611,Italy
Discover,6227 5231 8384 3270,2910,645,$24513,8,2022,Everly Orr,Elba Place 4964,Philippines
China UnionPay,6210 4565 0518 9529,3682,782,$26928,9,2022,Santo Nunez,Gautrey Road 7874,Luxembourg
JCB,3538 8868 5885 4968,8983,995,$5074,3,2022,Kevin Mclaughlin,Devonport Passage 4875,Liechtenstein

**Comment by valeciawolf34** [comment]
Valecia G Rodriguez

**Comment by calren** [comment]
Thanks for this @hadif66! We merged [this pull request](https://github.com/android/play-billing-samples/pull/378) for the fix, so we'll be closing this PR. Sorry for the delay in the review.

**Pull request closed without merging**
