### PR TITLE
fix debug message for endDataSourceConnections

### PR DESCRIPTION
**Pull request by nagamatu**
fix typo for endDataSourceConnections debug message

### CODE REVIEW

**Comment by nagamatu** [comment]
I signed it! and we'll verify it.

2020年3月18日(水) 10:13 googlebot <notifications@github.com>:

**Comment by nagamatu** [comment]
I fixed it.

**Comment by nagamatu** [comment]
@googlebot I fixed it.

**Comment by nagamatu** [comment]
@googlebot I consent.

**Comment by TE-tatuonagamatu** [comment]
@googlebot I consent.

**Comment by calren** [comment]
Thanks for the fix @nagamatu !

**Pull request merged**
